### ISSUE TITLE
Network layout algorithms

### ISSUE THREAD

**Issue by devmessias** [fury-gl/helios#7]
## TODO

- [ ] MDE
    - [x]  Generic Penalties
    - [x] Push and Pull 
    - [ ] Losses
    - [x] Centered Constrain
    - [x] Standardized Constrain
    - [x] Anchored Constrains
    - [x] Weights
    - [ ] Allows to choose the device (GPU)
    - [x] Tests
    - [x] Examples
    - [x] Docs 
 - [ ] HeliosFr
    - [x] Simple Version
    - [ ] expose gravity parameter (@filipinascimento task in heliosnet/helios-core)
    - [ ] Fix step interrupt method (@filipinascimento task in  heliosnet/helios-core)
    - [ ] Weights (@filipinascimento  heliosnet/helios-core)
    - [x] Tests
    - [x] Examples
    - [x] Docs
 - [x] CuGraph ForceAtlas2
     - [x] Tests
     - [x] Docs 
     - [x] Examples
